swagger: '2.0'
info:
  title: mblab
  description: No description
  version: v1
schemes:
  - https
paths:
  /user:
    post:
      summary: Create user
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
          required: true
      responses: &ref_0
        '200':
          description: OK
    get:
      summary: GetAllUser
      parameters: []
      responses: *ref_0
  /user/1:
    get:
      summary: GetUserPerId
      parameters: []
      responses: *ref_0
  /event:
    post:
      summary: CreateNewEvent
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              price:
                type: number
              name:
                type: string
              describe:
                type: string
              date:
                type: string
          required: true
      responses: *ref_0
    get:
      summary: GetAllEvents
      parameters: []
      responses: *ref_0
  /event/1:
    get:
      summary: GetEventPerId
      parameters: []
      responses: *ref_0
  /ticket:
    post:
      summary: CreateTicket
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              event_id:
                type: number
              user_id:
                type: number
          required: true
      responses: *ref_0
